Feature: Request-id propagation on every response

  The backend's request_logging task wires Fastify's per-request id
  (generated by Fastify, or read from an inbound `x-request-id`
  header) into the response as `x-request-id`. This gives clients and
  downstream load balancers / log aggregators a stable correlation
  handle from the wire to the server's structured log lines.

  Refinement: tasks/refinements/backend/request_logging.md
  ADRs:        docs/adr/0023-web-framework-fastify.md,
               docs/adr/0022-no-throwaway-verifications.md
  TaskJuggler: backend.api_skeleton.request_logging

  Scenario: every response carries a non-empty x-request-id header
    Given an HTTP server built from createServer
    When a GET request is sent to "/"
    Then the response status is 200
    And the response has a non-empty "x-request-id" header
