// `globalKeymap` — the single declarative source of truth enumerating
// every moderator keyboard shortcut as structured data.
//
// Refinement: tasks/refinements/moderator-ui/mod_global_keymap.md
//
// This module does NOT wire any listener. It is a data table consumed
// by two call sites:
//
//   1. `mod_keymap_help_overlay` (the dependent sibling) renders each
//      entry as `<chord> : <localized label>`.
//   2. `useGlobalKeymap` (the action-chord dispatcher) reads the
//      action-class entries to bind the cross-cutting chords.
//
// The single-letter `kind` / `edge-role` / `meta-move-kind` rows are
// GENERATED by iterating the canonical methodology tables in
// `@a-conversa/i18n-catalogs` so the registry cannot drift from the
// methodology source of truth (a Vitest drift-guard asserts equality).
// The `action` / `navigation` / `mode` rows are declared literally with
// their chords and `reachable` flags.
//
// Per the english-mnemonic shortcut policy (ADR 0024) the chord is
// stored STRUCTURALLY — `{ key, platformModifier, shift }` — and the
// label is referenced indirectly via `labelKey`. The overlay composes
// the platform-specific glyph (`Cmd/Ctrl+S`) and the localized label;
// no chord string is translated.

import {
  EDGE_ROLES,
  EDGE_ROLE_TO_SHORTCUT,
  KIND_TO_SHORTCUT,
  META_MOVE_KINDS,
  META_MOVE_KIND_TO_SHORTCUT,
  METHODOLOGY_KINDS,
} from '@a-conversa/i18n-catalogs';

/**
 * A structured keyboard chord. The base `key` is the lowercased form
 * matched against `event.key.toLowerCase()` (`'f'`, `'enter'`,
 * `'escape'`, `'s'`). `platformModifier` means `metaKey` on macOS /
 * `ctrlKey` elsewhere — the Cmd/Ctrl chord family. `shift` is an exact
 * requirement. Absent modifier fields mean the modifier must be absent.
 */
export type Chord = {
  key: string;
  platformModifier?: boolean;
  shift?: boolean;
};

/**
 * One row of the moderator keymap. `id` is stable (`'action.snapshot'`,
 * `'kind.fact'`). `reachable: false` marks an entry that is declared
 * for completeness (so the help overlay can show the planned binding)
 * but has no live handler yet.
 */
export type GlobalShortcut = {
  id: string;
  category: 'kind' | 'edge-role' | 'meta-move-kind' | 'mode' | 'action' | 'navigation';
  chord: Chord;
  labelKey: string;
  reachable: boolean;
};

// --- Generated single-letter entries (derived, never duplicated) -----

const kindShortcuts: readonly GlobalShortcut[] = METHODOLOGY_KINDS.map(
  (kind): GlobalShortcut => ({
    id: `kind.${kind}`,
    category: 'kind',
    chord: { key: KIND_TO_SHORTCUT[kind] },
    labelKey: `methodology.kind.${kind}`,
    reachable: true,
  }),
);

const edgeRoleShortcuts: readonly GlobalShortcut[] = EDGE_ROLES.map(
  (role): GlobalShortcut => ({
    id: `edge-role.${role}`,
    category: 'edge-role',
    chord: { key: EDGE_ROLE_TO_SHORTCUT[role] },
    labelKey: `methodology.edgeRole.${role}.label`,
    reachable: true,
  }),
);

const metaMoveKindShortcuts: readonly GlobalShortcut[] = META_MOVE_KINDS.map(
  (kind): GlobalShortcut => ({
    id: `meta-move-kind.${kind}`,
    category: 'meta-move-kind',
    chord: { key: META_MOVE_KIND_TO_SHORTCUT[kind] },
    // Meta-move kinds share the methodology annotation-kind labels.
    labelKey: `methodology.annotationKind.${kind}`,
    reachable: true,
  }),
);

// --- Declared action / navigation / mode entries --------------------

const actionShortcuts: readonly GlobalShortcut[] = [
  {
    // Propose stays textarea-owned (Decision §4); declared reachable
    // because it works today, but the dispatcher does NOT bind it.
    id: 'action.propose',
    category: 'action',
    chord: { key: 'enter', platformModifier: true },
    labelKey: 'moderator.proposeAction.label',
    reachable: true,
  },
  {
    // Snapshot — consolidated into `useGlobalKeymap` (folds in the
    // retired `useSnapshotShortcut`).
    id: 'action.snapshot',
    category: 'action',
    chord: { key: 's', platformModifier: true },
    labelKey: 'moderator.snapshotAction.label',
    reachable: true,
  },
  {
    // Commit — live (mod_proposal_selection_commit_chord). Bound in
    // `useGlobalKeymap` via the `useProposalCommitChord()` bridge; commits
    // the currently-selected pending proposal when its gate is open.
    id: 'action.commit',
    category: 'action',
    chord: { key: 'enter', platformModifier: true, shift: true },
    labelKey: 'moderator.commitButton.label',
    reachable: true,
  },
];

const navigationShortcuts: readonly GlobalShortcut[] = [
  {
    // Esc — exit-mode / clear-target. Backed by the existing
    // mode-aware branch in `captureKeymap`; registered here, not
    // re-bound (Decision §6).
    id: 'navigation.esc',
    category: 'navigation',
    chord: { key: 'escape' },
    labelKey: 'moderator.globalKeymap.escLabel',
    reachable: true,
  },
  {
    // Help — the `?` overlay toggle. Bound in its own
    // `useKeymapHelpShortcut` hook (a bare-key navigation chord with an
    // editable-target bail, the opposite of the action-chord family —
    // mod_keymap_help_overlay Decision §2), NOT in `useGlobalKeymap`.
    // Registered here so the overlay can document how it is opened — a
    // registry row is a description, not a binding site.
    id: 'navigation.help',
    category: 'navigation',
    chord: { key: '?' },
    labelKey: 'moderator.globalKeymap.helpLabel',
    reachable: true,
  },
];

const modeShortcuts: readonly GlobalShortcut[] = [
  {
    // Mode-entry chords are outside this leaf's title and not live
    // today (modes are entered via context menu / buttons). Declared
    // `reachable: false` so the overlay can show the planned set
    // (Decision §7).
    id: 'mode.decompose',
    category: 'mode',
    chord: { key: 'd', platformModifier: true },
    labelKey: 'moderator.modeBanner.decompose.label',
    reachable: false,
  },
  {
    id: 'mode.warrant-elicitation',
    category: 'mode',
    chord: { key: 'w', platformModifier: true },
    labelKey: 'moderator.modeBanner.warrant-elicitation.label',
    reachable: false,
  },
  {
    id: 'mode.operationalization',
    category: 'mode',
    chord: { key: 'o', platformModifier: true },
    labelKey: 'moderator.modeBanner.operationalization.label',
    reachable: false,
  },
];

/**
 * The ordered moderator keymap: kind → edge-role → meta-move-kind →
 * action → navigation → mode. Single source of truth for the help
 * overlay and the action-chord dispatcher.
 */
export const GLOBAL_KEYMAP: readonly GlobalShortcut[] = [
  ...kindShortcuts,
  ...edgeRoleShortcuts,
  ...metaMoveKindShortcuts,
  ...actionShortcuts,
  ...navigationShortcuts,
  ...modeShortcuts,
];
