// Step definitions for tests/behavior/backend/oauth-callback.feature.
//
// Refinement: tasks/refinements/backend/oauth_callback_handler.md
// ADRs:        docs/adr/0002-auth-self-hosted-oidc-authelia.md,
//              docs/adr/0017-mock-oauth-authelia-users-file.md,
//              docs/adr/0022-no-throwaway-verifications.md,
//              docs/adr/0023-web-framework-fastify.md
// TaskJuggler: backend.auth.oauth_callback_handler
//
// **What this layer exercises.** The full handler chain end-to-end:
// `GET /auth/login` generates the PKCE/state/nonce trio and stores it
// in the flow-state store; `GET /auth/callback` validates the state
// against the store, runs the (stubbed) token exchange + id_token
// validation, and upserts a `users` row in the pglite-backed DB.
// What's stubbed:
//
//   - The `Configuration` is `__buildStubConfiguration`-built (no
//     network discovery).
//   - `authorizationCodeGrant` is overridden via the plugin's
//     `completeFlowOptions` to return a deterministic token response
//     carrying a configurable `sub` claim.
//   - The PG pool is a thin adapter over the world's PGlite handle
//     so the INSERT...ON CONFLICT actually runs against a real
//     migrated schema (the `0001_users.sql` table).
//
// What's real:
//
//   - Fastify routing, the error-handler plugin's envelope, the
//     OpenAPI schema validation (the `state` querystring requirement
//     fires Fastify's validator on the missing-state case).
//   - The flow-state store's `put` / `take` semantics.
//   - The users-table upsert SQL — runs against the migrated
//     `users` table in pglite.
//
// Per ADR 0022, this Cucumber layer is the regression test for the
// end-to-end wiring; the Vitest layer covers pure-logic primitives
// in isolation.

import { After, Given, Then, When } from '@cucumber/cucumber';
import { strict as assert } from 'node:assert';

import {
  __buildStubConfiguration,
  __buildTestAuthApp,
  createFlowStateStore,
  type AuthRoutesOptions,
} from '../../../apps/server/src/auth/index.js';
import type { AConversaWorld, QueryResult } from '../support/world.js';

// Type the app via the helper's return type rather than importing
// `fastify` directly — the dep lives under `apps/server/node_modules`,
// which the test tsconfig doesn't resolve from this directory.
type FastifyAppInstance = Awaited<ReturnType<typeof __buildTestAuthApp>>;

interface OAuthCallbackScratch {
  authApp?: FastifyAppInstance;
  flowState?: ReturnType<typeof createFlowStateStore>;
  lastResponse?: {
    statusCode: number;
    body: string;
    headers: Record<string, unknown>;
  };
  // Track the state value generated by the most recent /auth/login so
  // the callback step can use it. Deterministic random in the plugin
  // options means we know what to expect.
  capturedState?: string;
  // Configurable sub claim for the stubbed token exchange — the
  // happy-path scenario varies the value per case.
  stubSub?: string;
}

function scratch(world: AConversaWorld): OAuthCallbackScratch {
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
  return world.scratch as OAuthCallbackScratch;
}

// Configuration used by the stubbed plugin. Matches what the dev
// `.env.example` produces (issuer hostname `authelia`, client id
// `aconversa-app-dev`, redirect URI under `http://localhost:3000`).
const OIDC_CONFIG = {
  issuerUrl: new URL('http://authelia:9091'),
  clientId: 'aconversa-app-dev',
  clientSecret: 'aconversa-app-dev-secret',
  appBaseUrl: 'http://localhost:3000',
  redirectUri: 'http://localhost:3000/auth/callback',
} as const;

// Stubbed `authorizationCodeGrant`. Reads `world.scratch.stubSub` so
// each scenario can pick which `sub` the token response carries.
function makeStubAuthCodeGrant(world: AConversaWorld) {
  return (): Promise<{
    access_token: string;
    token_type: string;
    claims: () => {
      sub: string;
      iss: string;
      aud: string;
      iat: number;
      exp: number;
    };
  }> => {
    const sub = scratch(world).stubSub ?? 'alice';
    return Promise.resolve({
      access_token: 'mock-access-token',
      token_type: 'Bearer',
      claims: () => ({
        sub,
        iss: 'http://authelia:9091',
        aud: 'aconversa-app-dev',
        iat: 0,
        exp: 0,
      }),
    });
  };
}

Given(
  'the auth server is built with a stubbed OIDC client and pglite-backed pool',
  async function (this: AConversaWorld) {
    const s = scratch(this);
    const flowState = createFlowStateStore({ ttlMs: 60_000 });
    s.flowState = flowState;

    // Deterministic random so the test can know what state value
    // /auth/login generated.
    const beginFlowOptions = {
      randomState: (): string => 'TEST-STATE-1',
      randomNonce: (): string => 'TEST-NONCE-1',
      randomPKCECodeVerifier: (): string => 'TEST-VERIFIER-1',
      calculatePKCECodeChallenge: (_v: string): Promise<string> =>
        Promise.resolve('TEST-CHALLENGE-1'),
      buildAuthorizationUrl: (
        _cfg: unknown,
        params: URLSearchParams | Record<string, string>,
      ): URL => {
        const sp = params instanceof URLSearchParams ? params : new URLSearchParams(params);
        return new URL(`http://authelia:9091/auth?${sp.toString()}`);
      },
    } satisfies NonNullable<AuthRoutesOptions['beginFlowOptions']>;

    // The production `authorizationCodeGrant` signature is the full
    // openid-client overload; the stub only satisfies the subset we
    // read (`.claims().sub`). Narrowed through `never` and pinned
    // via `satisfies` so it fits the `AuthRoutesOptions` shape under
    // `exactOptionalPropertyTypes`.
    const completeFlowOptions = {
      authorizationCodeGrant: makeStubAuthCodeGrant(this) as never,
    } satisfies NonNullable<AuthRoutesOptions['completeFlowOptions']>;

    // Adapter — translate the DbPool surface onto the world's PGlite
    // handle. PGlite's `query(text, params?)` returns `Results<T>`
    // (with `.rows`), which is structurally compatible with our DbPool's
    // `{ rows: T[] }` return type. We re-host the call to keep the
    // adapter's surface to a single method.
    const dbHandle = this.db;
    const pool = {
      async query<TRow extends Record<string, unknown>>(
        text: string,
        params?: ReadonlyArray<unknown>,
      ): Promise<{ rows: TRow[] }> {
        const result = await dbHandle.query<TRow>(text, params as unknown[] | undefined);
        return { rows: result.rows };
      },
    };

    const app = await __buildTestAuthApp({
      oidcConfig: { ...OIDC_CONFIG },
      oidcClient: __buildStubConfiguration(
        OIDC_CONFIG.issuerUrl,
        OIDC_CONFIG.clientId,
        OIDC_CONFIG.clientSecret,
      ),
      flowState,
      pool,
      beginFlowOptions,
      completeFlowOptions,
      // Pin the pending-cookie HMAC secret so the callback can sign
      // without reading process.env. Disable Secure so the cookie
      // round-trips over Fastify's in-process inject stream.
      sessionTokenSecret: 'test-session-secret',
      cookieSecure: false,
    });
    s.authApp = app;
  },
);

// Note: the `Given('a user with oauth_subject {string} exists', ...)` step
// is owned by tests/behavior/steps/users.steps.ts. Cucumber's step library
// is shared across step files; we reuse the existing definition here
// rather than redefine it (Cucumber would throw on a duplicate regex).

When('I GET \\/auth\\/login', async function (this: AConversaWorld) {
  const s = scratch(this);
  const app = s.authApp;
  assert.ok(app, 'auth app not initialized — Given step missing');
  const response = await app.inject({ method: 'GET', url: '/auth/login' });
  s.lastResponse = {
    statusCode: response.statusCode,
    body: response.body,
    headers: response.headers,
  };
  // Capture the generated state from the Location header so the
  // callback step can use it.
  const loc = response.headers['location'];
  if (typeof loc === 'string') {
    const url = new URL(loc);
    const stateValue = url.searchParams.get('state');
    if (stateValue !== null) {
      s.capturedState = stateValue;
    } else {
      delete s.capturedState;
    }
  }
});

// Note: `Then('the response status is {int}', ...)` is owned by
// tests/behavior/steps/http-server.steps.ts. We share its lastResponse
// carrier (also keyed on `scratch().lastResponse` in that file's typed
// shape, structurally compatible with ours).

Then(
  'the Location header points at {string}',
  function (this: AConversaWorld, expectedPrefix: string) {
    const res = scratch(this).lastResponse;
    assert.ok(res, 'no response captured — When step missing');
    const loc = res.headers['location'];
    assert.equal(typeof loc, 'string', 'expected a Location header');
    assert.ok(
      typeof loc === 'string' && loc.startsWith(expectedPrefix),
      `expected Location to start with ${expectedPrefix}; got ${String(loc)}`,
    );
  },
);

When(
  'I GET the callback URL with the stored state and a stubbed sub {string}',
  async function (this: AConversaWorld, sub: string) {
    const s = scratch(this);
    const app = s.authApp;
    assert.ok(app, 'auth app not initialized');
    assert.ok(s.capturedState, 'no state captured from /auth/login');
    s.stubSub = sub;
    const response = await app.inject({
      method: 'GET',
      url: `/auth/callback?code=AUTHCODE&state=${encodeURIComponent(s.capturedState)}`,
    });
    s.lastResponse = {
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    };
  },
);

When('I GET the callback URL with a deliberately bad state', async function (this: AConversaWorld) {
  const s = scratch(this);
  const app = s.authApp;
  assert.ok(app, 'auth app not initialized');
  const response = await app.inject({
    method: 'GET',
    url: '/auth/callback?code=AUTHCODE&state=THIS-STATE-IS-NOT-STORED',
  });
  s.lastResponse = {
    statusCode: response.statusCode,
    body: response.body,
    headers: response.headers,
  };
});

Then(
  "the response body's oauthSubject is {string}",
  function (this: AConversaWorld, expected: string) {
    const res = scratch(this).lastResponse;
    assert.ok(res, 'no response captured');
    const body = JSON.parse(res.body) as { oauthSubject?: unknown };
    assert.equal(body.oauthSubject, expected);
  },
);

Then("the response body's sub is {string}", function (this: AConversaWorld, expected: string) {
  const res = scratch(this).lastResponse;
  assert.ok(res, 'no response captured');
  const body = JSON.parse(res.body) as { sub?: unknown };
  assert.equal(body.sub, expected);
});

Then(
  "the response body's error.code is {string}",
  function (this: AConversaWorld, expected: string) {
    const res = scratch(this).lastResponse;
    assert.ok(res, 'no response captured');
    const body = JSON.parse(res.body) as { error?: { code?: unknown } };
    assert.equal(body.error?.code, expected);
  },
);

Then(
  'a users row exists with oauth_subject {string}',
  async function (this: AConversaWorld, oauthSubject: string) {
    const result = (await this.db.query(
      'SELECT id, oauth_subject, screen_name FROM users WHERE oauth_subject = $1',
      [oauthSubject],
    )) as QueryResult<{ id: string; oauth_subject: string; screen_name: string }>;
    assert.ok(
      result.rows.length > 0,
      `expected a users row with oauth_subject=${oauthSubject}; found none`,
    );
  },
);

Then(
  "the users row's screen_name is {string}",
  async function (this: AConversaWorld, expected: string) {
    // The most-recently-created row's screen name — for the
    // happy-path scenario the fresh INSERT carries the placeholder.
    const result = (await this.db.query(
      'SELECT screen_name FROM users ORDER BY created_at DESC LIMIT 1',
    )) as QueryResult<{ screen_name: string }>;
    assert.ok(result.rows.length > 0, 'no users rows found');
    assert.equal(result.rows[0]?.screen_name, expected);
  },
);

Then(
  'exactly one users row exists with oauth_subject {string}',
  async function (this: AConversaWorld, oauthSubject: string) {
    const result = (await this.db.query(
      'SELECT COUNT(*)::int AS count FROM users WHERE oauth_subject = $1',
      [oauthSubject],
    )) as QueryResult<{ count: number }>;
    assert.equal(result.rows[0]?.count, 1);
  },
);

After(async function (this: AConversaWorld) {
  const s = scratch(this);
  if (s.authApp) {
    await s.authApp.close();
    delete s.authApp;
  }
});
