// `make unblocked` — print, per milestone, the leaf tasks that are currently
// unblocked and ready to pick up.
//
// Approach
// --------
// TaskJuggler's `!`/`!!` relative-depends syntax and container-deps
// inheritance are fiddly enough that we don't want to re-implement them.
// Instead we lean on tj3 to do the resolution for us:
//
//   1. Synthesise a temporary `.tjp` that `include`s nothing useful but
//      copies the body of `project.tjp` verbatim and appends an extra
//      `taskreport` of `formats csv` with `id, name, complete, effort,
//      precursors`.
//   2. Run `tj3 --silent --report unblockedcsv <tempfile>`. The CSV
//      lands at `report/<title>.csv` (the `outputdir "report"` in
//      `project.tjp` wins over `-o`).
//   3. Parse the CSV. tj3 emits:
//        - `Id`         — fully-qualified task ID (e.g. `backend_hardening.auth_hardening.foo`)
//        - `Name`       — display name (leading spaces encode depth)
//        - `Completion` — `"NN%"`, with container rows showing the
//                         aggregate (only 100% iff every leaf is 100%)
//        - `Effort`     — number in `loadunit` (we set `days`)
//        - `Precursors` — `Name (fully.qualified.id) ]->[ YYYY-MM-DD`
//                         entries separated by `, `. tj3 has already
//                         inherited container-level depends down to each
//                         leaf, so the precursor list on a leaf row IS
//                         the resolved direct-dep set.
//   4. Identify leaves (any row whose Id is not a strict prefix of any
//      other row's Id). Identify milestones (rows under `milestones.`,
//      which is the only container that uses `milestone` in our WBS —
//      see tasks/99-milestones.tji).
//   5. For each milestone, compute its **gating set of leaves** by
//      walking precursors transitively: container precursors expand
//      to their contained leaves, milestone-on-milestone precursors
//      expand to that other milestone's gating set, and every leaf
//      added to the set has its own precursors walked the same way.
//      The transitive walk is what catches inherited container-level
//      deps — e.g. a leaf X named explicitly by the milestone may
//      inherit `depends !ParentTask` from its `.tji` parent block; the
//      sibling leaves under ParentTask must complete for X to complete,
//      so they belong in the gating set even when not named directly.
//   6. Within the gating set, a leaf is **unblocked** iff its own
//      direct precursor set (expanded to leaves) is fully complete and
//      the leaf itself is incomplete. Print those, plus counts for the
//      blocked + already-complete leaves.
//   7. In the full (unfiltered) report, also print **orphans**: leaf
//      tasks in NO milestone's gating set — nothing in the plan
//      transitively requires them. These are the audit target for "wire
//      to a milestone or descope".

import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');

const PROJECT_TJP = resolve(REPO_ROOT, 'project.tjp');
const MILESTONES_TJI = resolve(REPO_ROOT, 'tasks/99-milestones.tji');
const REPORT_DIR = resolve(REPO_ROOT, 'report');
const TEMP_TJP = resolve(REPO_ROOT, '.unblocked-report.tjp');
const TEMP_CSV = resolve(REPORT_DIR, 'UnblockedReport.csv');

interface TaskRow {
  id: string;
  name: string; // trimmed
  completePct: number; // 0..100
  effortDays: number;
  precursorIds: string[]; // fully-qualified
}

function runTj3(): TaskRow[] {
  const projectBody = readFileSync(PROJECT_TJP, 'utf8');
  const extraReport = `

# Auto-generated by scripts/unblocked.ts. Do not commit this file.
taskreport unblockedcsv "UnblockedReport" {
  formats csv
  columns id, name, complete, effort, precursors
  hidetask 0
  loadunit days
}
`;
  writeFileSync(TEMP_TJP, projectBody + extraReport, 'utf8');
  mkdirSync(REPORT_DIR, { recursive: true });
  try {
    const res = spawnSync('tj3', ['--silent', '--report', 'unblockedcsv', TEMP_TJP], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    });
    if (res.status !== 0) {
      process.stderr.write(res.stdout || '');
      process.stderr.write(res.stderr || '');
      throw new Error(`tj3 exited with status ${String(res.status)}`);
    }
    const csv = readFileSync(TEMP_CSV, 'utf8');
    return parseCsv(csv);
  } finally {
    try {
      rmSync(TEMP_TJP);
    } catch {
      // Best effort — the temp file is gitignored either way.
    }
  }
}

// Minimal CSV parser for the tj3 dialect: `;`-separated, string cells
// quoted with `"..."`, numeric cells unquoted (e.g. `26.5`). We have no
// embedded `"` or `;` inside string cells in this corpus — verified by
// spot-checking — so a small state machine suffices.
function parseCsv(csv: string): TaskRow[] {
  const lines = csv.split(/\r?\n/).filter((l) => l.length > 0);
  if (lines.length === 0) return [];
  const rows: TaskRow[] = [];
  for (let i = 1; i < lines.length; i++) {
    const cells = splitCsvLine(lines[i]!);
    if (cells.length < 5) continue;
    const id = cells[0]!;
    const name = cells[1]!.trim();
    const completePct = parseCompletion(cells[2]!);
    const effortDays = parseFloat(cells[3]!);
    const precursorIds = parsePrecursors(cells[4]!);
    rows.push({ id, name, completePct, effortDays, precursorIds });
  }
  return rows;
}

function splitCsvLine(line: string): string[] {
  const out: string[] = [];
  let i = 0;
  while (i < line.length) {
    if (line[i] === '"') {
      // Quoted cell.
      let end = i + 1;
      while (end < line.length && line[end] !== '"') end++;
      out.push(line.slice(i + 1, end));
      i = end + 1; // past closing quote
    } else {
      // Unquoted cell — read until `;` or EOL.
      let end = i;
      while (end < line.length && line[end] !== ';') end++;
      out.push(line.slice(i, end));
      i = end;
    }
    // Skip a single `;` separator.
    if (i < line.length && line[i] === ';') i++;
  }
  return out;
}

function parseCompletion(raw: string): number {
  // tj3 emits e.g. `100%`, `0%`, `88%`.
  const m = /^(\d+(?:\.\d+)?)\s*%/.exec(raw);
  if (!m) return 0;
  return parseFloat(m[1]!);
}

function parsePrecursors(raw: string): string[] {
  // Each precursor entry: `<name> (<fully.qualified.id>) ]->[ YYYY-MM-DD`.
  // Names can contain `(`, `)`, and `,`, so we anchor on the `(...) ]->[`
  // suffix instead of splitting on `, `.
  if (raw.length === 0) return [];
  const ids: string[] = [];
  const re = /\(([a-zA-Z0-9_.]+)\)\s*\]->\[/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(raw)) !== null) {
    ids.push(m[1]!);
  }
  return ids;
}

// --- Hierarchy + gating-set computation ---------------------------------

interface Graph {
  byId: Map<string, TaskRow>;
  // Direct children of each container, in CSV (= declaration) order.
  childrenOf: Map<string, string[]>;
  // Leaf descendants of every container/leaf, in declaration order.
  leavesOf: Map<string, string[]>;
}

function buildGraph(rows: TaskRow[]): Graph {
  const byId = new Map<string, TaskRow>();
  for (const r of rows) byId.set(r.id, r);

  // A row is a container iff some other row's id starts with `<this.id>.`.
  // Build the container set by walking every id's ancestor chain — cheaper
  // than the O(n^2) prefix scan over all id pairs.
  const containerIds = new Set<string>();
  for (const r of rows) {
    let cur = r.id;
    while (true) {
      const dot = cur.lastIndexOf('.');
      if (dot <= 0) break;
      cur = cur.slice(0, dot);
      containerIds.add(cur);
    }
  }

  const childrenOf = new Map<string, string[]>();
  for (const r of rows) {
    if (!containerIds.has(r.id)) continue;
    const prefix = r.id + '.';
    const directChildren = rows
      .filter((c) => {
        if (!c.id.startsWith(prefix)) return false;
        const rest = c.id.slice(prefix.length);
        return !rest.includes('.');
      })
      .map((c) => c.id);
    childrenOf.set(r.id, directChildren);
  }

  const leavesOf = new Map<string, string[]>();
  // Compute leaves bottom-up via recursion + memo.
  function leaves(id: string): string[] {
    const cached = leavesOf.get(id);
    if (cached !== undefined) return cached;
    if (!containerIds.has(id)) {
      const single = [id];
      leavesOf.set(id, single);
      return single;
    }
    const out: string[] = [];
    for (const c of childrenOf.get(id) ?? []) out.push(...leaves(c));
    leavesOf.set(id, out);
    return out;
  }
  for (const r of rows) leaves(r.id);

  return { byId, childrenOf, leavesOf };
}

// Expand a precursor id to leaves. Milestones (in `milestones.`) are
// treated as containers-of-zero-leaves themselves; their gating set is
// the union of their precursor expansions, computed below.
function expandToLeaves(g: Graph, id: string, milestoneIds: Set<string>): string[] {
  if (milestoneIds.has(id)) {
    // Should be handled by the caller via milestoneGatingSet; if we
    // reach here it's a recursive milestone-of-milestone link inside
    // gating-set computation — return empty (the caller will expand it
    // separately).
    return [];
  }
  return g.leavesOf.get(id) ?? [id];
}

function milestoneGatingSet(
  g: Graph,
  msId: string,
  milestoneIds: Set<string>,
  memo: Map<string, string[]>,
): string[] {
  const cached = memo.get(msId);
  if (cached !== undefined) return cached;
  // Tentative entry to break cycles (none expected, but cheap insurance).
  memo.set(msId, []);
  const ms = g.byId.get(msId);
  if (ms === undefined) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  const queue: string[] = [];
  const addLeaf = (leafId: string): void => {
    if (seen.has(leafId)) return;
    seen.add(leafId);
    out.push(leafId);
    queue.push(leafId);
  };
  const expandPrecursor = (preId: string): void => {
    if (milestoneIds.has(preId)) {
      for (const leaf of milestoneGatingSet(g, preId, milestoneIds, memo)) {
        addLeaf(leaf);
      }
    } else {
      for (const leaf of expandToLeaves(g, preId, milestoneIds)) {
        addLeaf(leaf);
      }
    }
  };
  for (const pre of ms.precursorIds) expandPrecursor(pre);
  // Transitive predecessor closure: a leaf inherits its `.tji` parent's
  // container-level depends, which may point at sibling containers whose
  // leaves are not directly named by the milestone. Those sibling leaves
  // still gate the milestone (the milestone-named leaf can't complete
  // until they do), so they belong in the gating set.
  while (queue.length > 0) {
    const leafId = queue.shift()!;
    const leaf = g.byId.get(leafId);
    if (leaf === undefined) continue;
    for (const pre of leaf.precursorIds) expandPrecursor(pre);
  }
  memo.set(msId, out);
  return out;
}

// A leaf is unblocked iff every leaf in its own direct-precursor
// expansion is 100% complete (and the leaf itself isn't).
function isLeafUnblocked(g: Graph, leafId: string, milestoneIds: Set<string>): boolean {
  const leaf = g.byId.get(leafId);
  if (leaf === undefined) return false;
  if (leaf.completePct >= 100) return false;
  for (const pre of leaf.precursorIds) {
    for (const depLeaf of expandToLeaves(g, pre, milestoneIds)) {
      const dep = g.byId.get(depLeaf);
      if (dep === undefined) continue;
      if (dep.completePct < 100) return false;
    }
  }
  return true;
}

// --- Orphan detection ----------------------------------------------------
// An "orphan" is a leaf task that is in NO milestone's gating set — i.e. no
// milestone transitively depends on it (directly, via a named precursor, or
// via inherited container-level depends). Nothing in the plan requires it, so
// completing it advances no milestone. This is strictly broader than "pure
// dependency-sink" (a leaf no other task names as a precursor): it also
// surfaces whole disconnected clusters whose tip happens to be depended-on by
// another orphan. The audit question for each is: should a milestone depend
// on it, or should it be descoped?
function computeOrphans(
  g: Graph,
  declared: string[],
  milestoneIds: Set<string>,
  gatingMemo: Map<string, string[]>,
): string[] {
  const reached = new Set<string>();
  for (const msId of declared) {
    if (!milestoneIds.has(msId)) continue;
    for (const leaf of milestoneGatingSet(g, msId, milestoneIds, gatingMemo)) {
      reached.add(leaf);
    }
  }
  const orphans: string[] = [];
  for (const r of g.byId.values()) {
    if (g.childrenOf.has(r.id)) continue; // container, not a leaf
    if (r.id.startsWith('milestones.')) continue; // milestones aren't tasks
    if (reached.has(r.id)) continue;
    orphans.push(r.id);
  }
  orphans.sort();
  return orphans;
}

// --- Milestone ordering from 99-milestones.tji --------------------------

function readMilestoneOrder(): string[] {
  const txt = readFileSync(MILESTONES_TJI, 'utf8');
  const lines = txt.split(/\r?\n/);
  const order: string[] = [];
  // Match `  task <id> "..."` lines. The milestones file has exactly one
  // outer `task milestones { ... }` block and direct children for each
  // milestone; we collect children in source order.
  let depth = 0;
  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith('task ')) {
      const m = /^task\s+(\w+)/.exec(line);
      if (m !== null && depth === 1) {
        order.push(`milestones.${m[1]!}`);
      }
    }
    // Track brace depth (very rough; works because the file has no
    // braces inside strings).
    for (const ch of raw) {
      if (ch === '{') depth++;
      else if (ch === '}') depth--;
    }
  }
  return order;
}

// --- Output -------------------------------------------------------------

function formatEffort(days: number): string {
  if (!Number.isFinite(days) || days === 0) return '';
  // Trim trailing zeros: 0.5, 1, 1.5, 2.25, ...
  const s = days.toFixed(2).replace(/0+$/, '').replace(/\.$/, '');
  return ` (${s}d)`;
}

function main(): void {
  const argv = process.argv.slice(2).filter((a) => a.length > 0);
  const filterArg = argv[0];

  const rows = runTj3();
  const g = buildGraph(rows);

  // Milestone IDs = rows under `milestones.` that are themselves
  // declared with `milestone`. In our WBS every direct child of the
  // `milestones` container is a milestone, so the prefix test is
  // sufficient — we double-check by intersecting with the source-order
  // list we read directly from the .tji.
  const declared = readMilestoneOrder();
  const milestoneIds = new Set(declared.filter((id) => g.byId.has(id)));

  let filterId: string | undefined;
  if (filterArg !== undefined) {
    const qualified = filterArg.startsWith('milestones.') ? filterArg : `milestones.${filterArg}`;
    if (!milestoneIds.has(qualified)) {
      process.stderr.write(`unblocked: milestone not found: ${filterArg}\n`);
      process.stderr.write(`Available milestones:\n`);
      for (const id of declared) {
        if (milestoneIds.has(id)) {
          process.stderr.write(`  ${id.replace(/^milestones\./, '')}\n`);
        }
      }
      process.exit(1);
    }
    filterId = qualified;
  }

  const gatingMemo = new Map<string, string[]>();
  const lines: string[] = [];

  for (const msId of declared) {
    if (filterId !== undefined && msId !== filterId) continue;
    const ms = g.byId.get(msId);
    if (ms === undefined) continue;
    if (!milestoneIds.has(msId)) continue;
    if (ms.completePct >= 100) {
      // Don't clutter the report with finished milestones.
      lines.push(`${msId.replace(/^milestones\./, '')}: ${ms.name}`);
      lines.push(`  COMPLETE — milestone already 100%`);
      lines.push('');
      continue;
    }
    const gating = milestoneGatingSet(g, msId, milestoneIds, gatingMemo);
    const complete: string[] = [];
    const blocked: string[] = [];
    const unblocked: string[] = [];
    for (const leafId of gating) {
      const leaf = g.byId.get(leafId);
      if (leaf === undefined) continue;
      if (leaf.completePct >= 100) {
        complete.push(leafId);
      } else if (isLeafUnblocked(g, leafId, milestoneIds)) {
        unblocked.push(leafId);
      } else {
        blocked.push(leafId);
      }
    }

    lines.push(`${msId.replace(/^milestones\./, '')}: ${ms.name}`);
    if (gating.length === 0) {
      lines.push(`  (no gating leaves — nothing to track)`);
    } else if (unblocked.length === 0 && blocked.length === 0) {
      lines.push(`  ALL GATING WORK COMPLETE — milestone ready to mark`);
      lines.push(`  COMPLETE: ${String(complete.length)} / ${String(gating.length)} leaves`);
    } else {
      lines.push(`  READY (${String(unblocked.length)} leaves):`);
      if (unblocked.length === 0) {
        lines.push(`    (none — every incomplete leaf still has open predecessors)`);
      } else {
        for (const id of unblocked) {
          const leaf = g.byId.get(id)!;
          lines.push(`    ${id}${formatEffort(leaf.effortDays)}`);
        }
      }
      lines.push(`  BLOCKED (still waiting on incomplete predecessors): ${String(blocked.length)}`);
      lines.push(`  COMPLETE: ${String(complete.length)} / ${String(gating.length)} leaves`);
    }
    lines.push('');
  }

  // Global orphan audit — only in the full (unfiltered) report, since it is
  // a plan-wide view rather than a per-milestone one.
  if (filterId === undefined) {
    const orphans = computeOrphans(g, declared, milestoneIds, gatingMemo);
    const incomplete = orphans.filter((id) => g.byId.get(id)!.completePct < 100);
    const complete = orphans.filter((id) => g.byId.get(id)!.completePct >= 100);
    lines.push('────────────────────────────────────────────────────────────');
    lines.push('ORPHANS — leaf tasks no milestone transitively depends on');
    lines.push('(nothing in the plan requires them — audit: wire to a milestone or descope)');
    lines.push('');
    lines.push(`  INCOMPLETE (${String(incomplete.length)}):`);
    if (incomplete.length === 0) {
      lines.push('    (none)');
    } else {
      for (const id of incomplete) {
        const leaf = g.byId.get(id)!;
        lines.push(`    ${id}${formatEffort(leaf.effortDays)} [${String(leaf.completePct)}%]`);
      }
    }
    lines.push(`  COMPLETE (${String(complete.length)}):`);
    if (complete.length === 0) {
      lines.push('    (none)');
    } else {
      for (const id of complete) lines.push(`    ${id}`);
    }
    lines.push('');
  }

  process.stdout.write(lines.join('\n'));
  if (!lines[lines.length - 1]?.endsWith('\n')) process.stdout.write('\n');
}

main();
