// Codegen — vendor the canonical `walkthrough` fixture into the server.
//
// Refinement: tasks/refinements/replay_test/test_mode_synthetic_scenario_library.md
// ADR:        docs/adr/0042-runtime-fixture-reuse-via-vendored-module.md
//
// Reads the canonical `walkthrough` fixture JSON from the
// `@a-conversa/test-fixtures` package source tree and emits a committed
// typed module (`src/test-mode/synthetic/walkthrough.data.ts`) the server
// runtime imports as a plain `const`. The runtime image prunes the
// `@a-conversa/test-fixtures` devDependency and copies only specific
// `dist` trees (Dockerfile), so the fixture data must be compiled TS
// under `apps/server/dist` to be reachable at runtime — including the
// e2e/compose environment. See ADR 0042 for the full rationale.
//
// Re-run after editing the canonical fixture:
//   pnpm -F @a-conversa/server gen:walkthrough-data
// then run prettier (`pnpm run format`). The `walkthrough.data.test.ts`
// drift-guard fails CI if the committed copy ever diverges from source.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

// The canonical fixture lives in the test-fixtures package source. The
// path is relative to this script (apps/server/scripts → repo root →
// packages/...); the drift-guard test resolves the same source.
const FIXTURE_DIR = join(
  here,
  '..',
  '..',
  '..',
  'packages',
  'test-fixtures',
  'src',
  'fixtures',
  'walkthrough',
);

const OUTPUT_PATH = join(here, '..', 'src', 'test-mode', 'synthetic', 'walkthrough.data.ts');

function readJson(name: string): unknown {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, name), 'utf8'));
}

function main(): void {
  const session = readJson('session.json');
  const participants = readJson('participants.json');
  const events = readJson('events.json');

  // Only the three fields the re-keyer reads are vendored (session,
  // participants, events) — meta/users are not consumed at runtime.
  const data = { session, participants, events };

  const banner = [
    '// GENERATED by apps/server/scripts/gen-walkthrough-data.ts — DO NOT EDIT BY HAND.',
    '//',
    '// Vendored snapshot of the canonical `walkthrough` test-fixture (ADR 0042).',
    '// Re-run `pnpm -F @a-conversa/server gen:walkthrough-data` then `pnpm run',
    '// format` after editing the canonical fixture. The drift-guard test',
    '// `walkthrough.data.test.ts` pins this against the source.',
    '',
    "import type { VendoredFixture } from './rekey.js';",
    '',
    `export const walkthroughFixtureData: VendoredFixture = ${JSON.stringify(data, null, 2)};`,
    '',
  ].join('\n');

  writeFileSync(OUTPUT_PATH, banner, 'utf8');
  const eventCount = Array.isArray(events) ? events.length : 0;
  process.stdout.write(
    `[gen-walkthrough-data] wrote ${OUTPUT_PATH} (${String(eventCount)} events)\n`,
  );
}

main();
